/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_just_do_springboot_bll_UserService */

#ifndef _Included_cn_just_do_springboot_bll_UserService
#define _Included_cn_just_do_springboot_bll_UserService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_just_do_springboot_bll_UserService
 * Method:    auth
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_just_1do_springboot_bll_UserService_auth
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
