/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_just_do_springboot_bll_UserService */

#ifndef _Included_cn_just_do_springboot_bll_UserService
#define _Included_cn_just_do_springboot_bll_UserService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_just_do_springboot_bll_UserService
 * Method:    auth
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_just_1do_springboot_bll_UserService_auth
  (JNIEnv *env, jobject obj);

/*
 * Class:     cn_just_do_springboot_bll_UserService
 * Method:    auth2
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_just_1do_springboot_bll_UserService_auth2
  (JNIEnv *env, jobject obj, jstring content);

/*
 * Class:     cn_just_do_springboot_bll_UserService
 * Method:    auth3
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_just_1do_springboot_bll_UserService_auth3
  (JNIEnv *env, jobject obj, jobjectArray objArray);

#ifdef __cplusplus
}
#endif
#endif
